# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_salesforce_custom_domain_salesforce_custom_domain_authorizer_new_o_auth_url_request import AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest

class TestAppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest(unittest.TestCase):
    """AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest:
        """Test AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest`
        """
        model = AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest()
        if include_optional:
            return AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest(
                config = [
                    openapi_client.models.app_authorizer_salesforce_custom_domain_salesforce_custom_domain_authorizer_new_o_auth_url_request_config_inner.appAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrl_request_config_inner(
                        subdomain = '', )
                    ],
                state = '',
                service_id = ''
            )
        else:
            return AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest(
        )
        """

    def testAppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest(self):
        """Test AppAuthorizerSalesforceCustomDomainSalesforceCustomDomainAuthorizerNewOAuthUrlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
