# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_s3_api import ServicesS3Api


class TestServicesS3Api(unittest.TestCase):
    """ServicesS3Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesS3Api()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_s3_s3_authorizer_create_service(self) -> None:
        """Test case for app_authorizer_s3_s3_authorizer_create_service

        Create service
        """
        pass


if __name__ == '__main__':
    unittest.main()
