# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.destinations_one_drive_api import DestinationsOneDriveApi


class TestDestinationsOneDriveApi(unittest.TestCase):
    """DestinationsOneDriveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DestinationsOneDriveApi()

    def tearDown(self) -> None:
        pass

    def test_app_destination_one_drive_one_drive_destination_action_authorization(self) -> None:
        """Test case for app_destination_one_drive_one_drive_destination_action_authorization

        List of authorization objects
        """
        pass

    def test_app_destination_one_drive_one_drive_destination_action_filename_patterns(self) -> None:
        """Test case for app_destination_one_drive_one_drive_destination_action_filename_patterns

        List of filename patterns
        """
        pass

    def test_app_destination_one_drive_one_drive_destination_action_write_modes(self) -> None:
        """Test case for app_destination_one_drive_one_drive_destination_action_write_modes

        List of write modes
        """
        pass

    def test_app_destination_one_drive_one_drive_destination_create(self) -> None:
        """Test case for app_destination_one_drive_one_drive_destination_create

        Create destination
        """
        pass


if __name__ == '__main__':
    unittest.main()
