# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_quickbooks_custom_quickbooks_custom_authorizer_new_o_auth_callback_request import AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest

class TestAppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest(unittest.TestCase):
    """AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest:
        """Test AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest`
        """
        model = AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest()
        if include_optional:
            return AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest(
                callback_url = 'https://my.app.com/callback?code=aaaaBBBBccc1234',
                config = openapi_client.models.quickbooks_custom_dto_authorizer.QuickbooksCustomDtoAuthorizer(
                    label = '', 
                    tenant = '', 
                    client_id = '', 
                    client_secret = '', 
                    redirect_uri = '', )
            )
        else:
            return AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest(
        )
        """

    def testAppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest(self):
        """Test AppAuthorizerQuickbooksCustomQuickbooksCustomAuthorizerNewOAuthCallbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
