# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_facebook_ads_api import ConnectorsFacebookAdsApi


class TestConnectorsFacebookAdsApi(unittest.TestCase):
    """ConnectorsFacebookAdsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsFacebookAdsApi()

    def tearDown(self) -> None:
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_account(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_account

        List of all accounts
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_ad_set(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_ad_set

        List of Ad sets
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_authorization(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_authorization

        List of authorization objects
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_campaign(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_campaign

        List of all campaigns
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_data_label(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_data_label

        List of all data labels
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_date_range(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_date_range

        Method for listing date range
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_level(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_level

        List of all reporting levels
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_metric(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_metric

        List of all metrics
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_optional_breakdown(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_optional_breakdown

        List of all optional breakdowns
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_action_time_breakdown(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_action_time_breakdown

        List of all time breakdowns
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_create_source(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_create_source

        Create FacebookAds source
        """
        pass

    def test_app_connector_facebook_ads_facebook_ads_connector_preview(self) -> None:
        """Test case for app_connector_facebook_ads_facebook_ads_connector_preview

        Data preview
        """
        pass


if __name__ == '__main__':
    unittest.main()
