# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_netsuite_api import ConnectorsNetsuiteApi


class TestConnectorsNetsuiteApi(unittest.TestCase):
    """ConnectorsNetsuiteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsNetsuiteApi()

    def tearDown(self) -> None:
        pass

    def test_app_connector_netsuite_netsuite_connector_action_attributes(self) -> None:
        """Test case for app_connector_netsuite_netsuite_connector_action_attributes

        List all attributes for the given object
        """
        pass

    def test_app_connector_netsuite_netsuite_connector_action_authorization(self) -> None:
        """Test case for app_connector_netsuite_netsuite_connector_action_authorization

        List of authorization objects
        """
        pass

    def test_app_connector_netsuite_netsuite_connector_action_object(self) -> None:
        """Test case for app_connector_netsuite_netsuite_connector_action_object

        Get Netsuite objects
        """
        pass

    def test_app_connector_netsuite_netsuite_connector_create_source(self) -> None:
        """Test case for app_connector_netsuite_netsuite_connector_create_source

        Create Netsuite source
        """
        pass

    def test_app_connector_netsuite_netsuite_connector_preview(self) -> None:
        """Test case for app_connector_netsuite_netsuite_connector_preview

        Data preview
        """
        pass


if __name__ == '__main__':
    unittest.main()
