# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_microsoft_dynamics365_api import ServicesMicrosoftDynamics365Api


class TestServicesMicrosoftDynamics365Api(unittest.TestCase):
    """ServicesMicrosoftDynamics365Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesMicrosoftDynamics365Api()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_microsoft_dynamics365_microsoft_dynamics365_authorizer_get_authorization_url(self) -> None:
        """Test case for app_authorizer_microsoft_dynamics365_microsoft_dynamics365_authorizer_get_authorization_url

        Get url for service authentication
        """
        pass

    def test_app_authorizer_microsoft_dynamics365_microsoft_dynamics365_authorizer_o_auth_process_callback(self) -> None:
        """Test case for app_authorizer_microsoft_dynamics365_microsoft_dynamics365_authorizer_o_auth_process_callback

        Create service
        """
        pass


if __name__ == '__main__':
    unittest.main()
