# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_google_play_custom_google_play_custom_authorizer_new_o_auth_callback_request import AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest

class TestAppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest(unittest.TestCase):
    """AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest:
        """Test AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest`
        """
        model = AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest()
        if include_optional:
            return AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest(
                callback_url = 'https://my.app.com/callback?code=aaaaBBBBccc1234',
                config = openapi_client.models.google_play_custom_dto_authorizer.GooglePlayCustomDtoAuthorizer(
                    label = '', 
                    client_id = '', 
                    client_secret = '', 
                    redirect_uri = '', )
            )
        else:
            return AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest(
        )
        """

    def testAppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest(self):
        """Test AppAuthorizerGooglePlayCustomGooglePlayCustomAuthorizerNewOAuthCallbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
