# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.destinations_intercom_export_api import DestinationsIntercomExportApi


class TestDestinationsIntercomExportApi(unittest.TestCase):
    """DestinationsIntercomExportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DestinationsIntercomExportApi()

    def tearDown(self) -> None:
        pass

    def test_app_connector_intercom_export_intercom_export_connector_action_file(self) -> None:
        """Test case for app_connector_intercom_export_intercom_export_connector_action_file

        List of files
        """
        pass


if __name__ == '__main__':
    unittest.main()
