# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_google_analytics_api import ConnectorsGoogleAnalyticsApi


class TestConnectorsGoogleAnalyticsApi(unittest.TestCase):
    """ConnectorsGoogleAnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsGoogleAnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_google_analytics_controller_action_account(self) -> None:
        """Test case for google_analytics_controller_action_account

        List of accounts
        """
        pass

    def test_google_analytics_controller_action_authorization(self) -> None:
        """Test case for google_analytics_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_google_analytics_controller_action_data_label(self) -> None:
        """Test case for google_analytics_controller_action_data_label

        List of data label objects
        """
        pass

    def test_google_analytics_controller_action_dimension(self) -> None:
        """Test case for google_analytics_controller_action_dimension

        List of dimension objects
        """
        pass

    def test_google_analytics_controller_action_load(self) -> None:
        """Test case for google_analytics_controller_action_load

        Create Google Analytics source
        """
        pass

    def test_google_analytics_controller_action_metric(self) -> None:
        """Test case for google_analytics_controller_action_metric

        List of metric objects
        """
        pass

    def test_google_analytics_controller_action_preview(self) -> None:
        """Test case for google_analytics_controller_action_preview

        Preview the data
        """
        pass

    def test_google_analytics_controller_action_property(self) -> None:
        """Test case for google_analytics_controller_action_property

        List of properties
        """
        pass

    def test_google_analytics_controller_action_segment(self) -> None:
        """Test case for google_analytics_controller_action_segment

        List of saved segments
        """
        pass

    def test_google_analytics_controller_action_view(self) -> None:
        """Test case for google_analytics_controller_action_view

        List of views
        """
        pass


if __name__ == '__main__':
    unittest.main()
