# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sftp_storage_request import SftpStorageRequest

class TestSftpStorageRequest(unittest.TestCase):
    """SftpStorageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SftpStorageRequest:
        """Test SftpStorageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SftpStorageRequest`
        """
        model = SftpStorageRequest()
        if include_optional:
            return SftpStorageRequest(
                label = '',
                type = '',
                o_auth_id = 56,
                path = ''
            )
        else:
            return SftpStorageRequest(
        )
        """

    def testSftpStorageRequest(self):
        """Test SftpStorageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
