# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_facebook_page_api import ConnectorsFacebookPageApi


class TestConnectorsFacebookPageApi(unittest.TestCase):
    """ConnectorsFacebookPageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsFacebookPageApi()

    def tearDown(self) -> None:
        pass

    def test_facebook_page_controller_action_authorization(self) -> None:
        """Test case for facebook_page_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_facebook_page_controller_action_data_label(self) -> None:
        """Test case for facebook_page_controller_action_data_label

        List all Facebook Page data labels
        """
        pass

    def test_facebook_page_controller_action_date_range(self) -> None:
        """Test case for facebook_page_controller_action_date_range

        Method for listing date range
        """
        pass

    def test_facebook_page_controller_action_default_data_label(self) -> None:
        """Test case for facebook_page_controller_action_default_data_label

        List all default data labels
        """
        pass

    def test_facebook_page_controller_action_default_metric(self) -> None:
        """Test case for facebook_page_controller_action_default_metric

        List all default metrics
        """
        pass

    def test_facebook_page_controller_action_load(self) -> None:
        """Test case for facebook_page_controller_action_load

        Create Facebook Page source
        """
        pass

    def test_facebook_page_controller_action_metric(self) -> None:
        """Test case for facebook_page_controller_action_metric

        List Facebook Page metrics
        """
        pass

    def test_facebook_page_controller_action_page(self) -> None:
        """Test case for facebook_page_controller_action_page

        List all available Facebook Pages
        """
        pass

    def test_facebook_page_controller_action_preview(self) -> None:
        """Test case for facebook_page_controller_action_preview

        Preview the data
        """
        pass


if __name__ == '__main__':
    unittest.main()
