# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_linkedin_static_api import ServicesLinkedinStaticApi


class TestServicesLinkedinStaticApi(unittest.TestCase):
    """ServicesLinkedinStaticApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesLinkedinStaticApi()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_linkedin_static_linkedin_static_authorizer_new(self) -> None:
        """Test case for app_authorizer_linkedin_static_linkedin_static_authorizer_new

        Authorize a service
        """
        pass


if __name__ == '__main__':
    unittest.main()
