# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_google_campaign_manager_api import ConnectorsGoogleCampaignManagerApi


class TestConnectorsGoogleCampaignManagerApi(unittest.TestCase):
    """ConnectorsGoogleCampaignManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsGoogleCampaignManagerApi()

    def tearDown(self) -> None:
        pass

    def test_google_campaign_manager_controller_action_authorization(self) -> None:
        """Test case for google_campaign_manager_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_google_campaign_manager_controller_action_load(self) -> None:
        """Test case for google_campaign_manager_controller_action_load

        Create Google Campaign Manager source
        """
        pass

    def test_google_campaign_manager_controller_action_preview(self) -> None:
        """Test case for google_campaign_manager_controller_action_preview

        Preview the data
        """
        pass

    def test_google_campaign_manager_controller_action_profile(self) -> None:
        """Test case for google_campaign_manager_controller_action_profile

        List of profile ids
        """
        pass

    def test_google_campaign_manager_controller_action_report_type(self) -> None:
        """Test case for google_campaign_manager_controller_action_report_type

        List Google Campaign Manager report types
        """
        pass


if __name__ == '__main__':
    unittest.main()
