# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.microsoft_ads_custom_dto_authorizer import MicrosoftAdsCustomDtoAuthorizer

class TestMicrosoftAdsCustomDtoAuthorizer(unittest.TestCase):
    """MicrosoftAdsCustomDtoAuthorizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MicrosoftAdsCustomDtoAuthorizer:
        """Test MicrosoftAdsCustomDtoAuthorizer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MicrosoftAdsCustomDtoAuthorizer`
        """
        model = MicrosoftAdsCustomDtoAuthorizer()
        if include_optional:
            return MicrosoftAdsCustomDtoAuthorizer(
                label = '',
                tenant_id = '',
                developer_token = '',
                client_id = '',
                client_secret = '',
                redirect_uri = ''
            )
        else:
            return MicrosoftAdsCustomDtoAuthorizer(
        )
        """

    def testMicrosoftAdsCustomDtoAuthorizer(self):
        """Test MicrosoftAdsCustomDtoAuthorizer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
