# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_tik_tok_api import ConnectorsTikTokApi


class TestConnectorsTikTokApi(unittest.TestCase):
    """ConnectorsTikTokApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsTikTokApi()

    def tearDown(self) -> None:
        pass

    def test_tik_tok_controller_action_advertiser(self) -> None:
        """Test case for tik_tok_controller_action_advertiser

        List of advertisers
        """
        pass

    def test_tik_tok_controller_action_audience_dimension(self) -> None:
        """Test case for tik_tok_controller_action_audience_dimension

        List of all audience dimensions
        """
        pass

    def test_tik_tok_controller_action_authorization(self) -> None:
        """Test case for tik_tok_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_tik_tok_controller_action_data_label(self) -> None:
        """Test case for tik_tok_controller_action_data_label

        List all data labels
        """
        pass

    def test_tik_tok_controller_action_data_level(self) -> None:
        """Test case for tik_tok_controller_action_data_level

        List of data levels
        """
        pass

    def test_tik_tok_controller_action_date_range(self) -> None:
        """Test case for tik_tok_controller_action_date_range

        Method for listing date range
        """
        pass

    def test_tik_tok_controller_action_id_dimension(self) -> None:
        """Test case for tik_tok_controller_action_id_dimension

        List of all ID dimensions
        """
        pass

    def test_tik_tok_controller_action_load(self) -> None:
        """Test case for tik_tok_controller_action_load

        Create TikTok source
        """
        pass

    def test_tik_tok_controller_action_metric(self) -> None:
        """Test case for tik_tok_controller_action_metric

        List all metrics
        """
        pass

    def test_tik_tok_controller_action_preview(self) -> None:
        """Test case for tik_tok_controller_action_preview

        Preview the data
        """
        pass

    def test_tik_tok_controller_action_report_type(self) -> None:
        """Test case for tik_tok_controller_action_report_type

        List of report types
        """
        pass

    def test_tik_tok_controller_action_time_dimension(self) -> None:
        """Test case for tik_tok_controller_action_time_dimension

        List of all time dimensions
        """
        pass


if __name__ == '__main__':
    unittest.main()
