# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_amazon_ads_data_extractor_api import ConnectorsAmazonAdsDataExtractorApi


class TestConnectorsAmazonAdsDataExtractorApi(unittest.TestCase):
    """ConnectorsAmazonAdsDataExtractorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsAmazonAdsDataExtractorApi()

    def tearDown(self) -> None:
        pass

    def test_amazon_ads_data_extractor_controller_action_load(self) -> None:
        """Test case for amazon_ads_data_extractor_controller_action_load

        Create Amazon Ads Data Extractor source
        """
        pass

    def test_amazon_ads_data_extractor_controller_action_preview(self) -> None:
        """Test case for amazon_ads_data_extractor_controller_action_preview

        Preview the data
        """
        pass


if __name__ == '__main__':
    unittest.main()
