# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_cockroach_db_api import ServicesCockroachDbApi


class TestServicesCockroachDbApi(unittest.TestCase):
    """ServicesCockroachDbApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesCockroachDbApi()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_cockroach_db_cockroach_db_authorizer_action_ssl(self) -> None:
        """Test case for app_authorizer_cockroach_db_cockroach_db_authorizer_action_ssl

        List of SSL options
        """
        pass


if __name__ == '__main__':
    unittest.main()
