# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_amazon_selling_partner_custom_amazon_selling_partner_custom_authorizer_get_authorization_url_request_config import AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig

class TestAppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig(unittest.TestCase):
    """AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig:
        """Test AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig`
        """
        model = AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig()
        if include_optional:
            return AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig(
                app_id = '',
                redirect_uri = '',
                scopes = [
                    ''
                    ]
            )
        else:
            return AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig(
                app_id = '',
                redirect_uri = '',
        )
        """

    def testAppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig(self):
        """Test AppAuthorizerAmazonSellingPartnerCustomAmazonSellingPartnerCustomAuthorizerGetAuthorizationUrlRequestConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
