# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_linkedin_static_linkedin_static_authorizer_new_request import AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest

class TestAppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest(unittest.TestCase):
    """AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest:
        """Test AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest`
        """
        model = AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest()
        if include_optional:
            return AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest(
                service = 'linkedin_static',
                data = openapi_client.models.linkedin_static_dto_authorizer.LinkedinStaticDtoAuthorizer()
            )
        else:
            return AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest(
        )
        """

    def testAppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest(self):
        """Test AppAuthorizerLinkedinStaticLinkedinStaticAuthorizerNewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
