# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.certificates_api import CertificatesApi


class TestCertificatesApi(unittest.TestCase):
    """CertificatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CertificatesApi()

    def tearDown(self) -> None:
        pass

    def test_certificate_controller_create(self) -> None:
        """Test case for certificate_controller_create

        """
        pass

    def test_certificate_controller_delete(self) -> None:
        """Test case for certificate_controller_delete

        """
        pass

    def test_certificate_controller_detail(self) -> None:
        """Test case for certificate_controller_detail

        """
        pass

    def test_certificate_controller_list(self) -> None:
        """Test case for certificate_controller_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
