# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_account_controller_delete_customer_member(self) -> None:
        """Test case for account_controller_delete_customer_member

        """
        pass

    def test_account_controller_delete_invited_member(self) -> None:
        """Test case for account_controller_delete_invited_member

        """
        pass

    def test_account_controller_delete_invited_member_by_id(self) -> None:
        """Test case for account_controller_delete_invited_member_by_id

        """
        pass

    def test_account_controller_get_customer_invited_members(self) -> None:
        """Test case for account_controller_get_customer_invited_members

        """
        pass

    def test_account_controller_get_customer_members(self) -> None:
        """Test case for account_controller_get_customer_members

        """
        pass

    def test_account_controller_invite_member(self) -> None:
        """Test case for account_controller_invite_member

        """
        pass


if __name__ == '__main__':
    unittest.main()
