# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.google_sheets_storage_request import GoogleSheetsStorageRequest

class TestGoogleSheetsStorageRequest(unittest.TestCase):
    """GoogleSheetsStorageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleSheetsStorageRequest:
        """Test GoogleSheetsStorageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleSheetsStorageRequest`
        """
        model = GoogleSheetsStorageRequest()
        if include_optional:
            return GoogleSheetsStorageRequest(
                label = '',
                type = '',
                o_auth_id = 56
            )
        else:
            return GoogleSheetsStorageRequest(
        )
        """

    def testGoogleSheetsStorageRequest(self):
        """Test GoogleSheetsStorageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
