# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_webex_api import ConnectorsWebexApi


class TestConnectorsWebexApi(unittest.TestCase):
    """ConnectorsWebexApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsWebexApi()

    def tearDown(self) -> None:
        pass

    def test_app_connector_webex_webex_connector_action_meeting_site(self) -> None:
        """Test case for app_connector_webex_webex_connector_action_meeting_site

        List of Webex meetings sites
        """
        pass

    def test_app_connector_webex_webex_connector_action_meetings(self) -> None:
        """Test case for app_connector_webex_webex_connector_action_meetings

        List of Webex meetings
        """
        pass

    def test_app_connector_webex_webex_connector_action_meetings_with_polls(self) -> None:
        """Test case for app_connector_webex_webex_connector_action_meetings_with_polls

        List of Webex meetings
        """
        pass


if __name__ == '__main__':
    unittest.main()
