# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_facebook_static_facebook_static_authorizer_new_request import AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest

class TestAppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest(unittest.TestCase):
    """AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest:
        """Test AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest`
        """
        model = AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest()
        if include_optional:
            return AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest(
                service = 'facebook_static',
                data = openapi_client.models.facebook_static_dto_authorizer.FacebookStaticDtoAuthorizer()
            )
        else:
            return AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest(
        )
        """

    def testAppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest(self):
        """Test AppAuthorizerFacebookStaticFacebookStaticAuthorizerNewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
