# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_snapchat_lookup_api import ConnectorsSnapchatLookupApi


class TestConnectorsSnapchatLookupApi(unittest.TestCase):
    """ConnectorsSnapchatLookupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsSnapchatLookupApi()

    def tearDown(self) -> None:
        pass

    def test_snapchat_lookup_controller_action_account(self) -> None:
        """Test case for snapchat_lookup_controller_action_account

        List of accounts
        """
        pass

    def test_snapchat_lookup_controller_action_attribute(self) -> None:
        """Test case for snapchat_lookup_controller_action_attribute

        List of attributes
        """
        pass

    def test_snapchat_lookup_controller_action_authorization(self) -> None:
        """Test case for snapchat_lookup_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_snapchat_lookup_controller_action_level(self) -> None:
        """Test case for snapchat_lookup_controller_action_level

        List of levels
        """
        pass

    def test_snapchat_lookup_controller_action_load(self) -> None:
        """Test case for snapchat_lookup_controller_action_load

        Create Snapchat Lookup source
        """
        pass

    def test_snapchat_lookup_controller_action_organization(self) -> None:
        """Test case for snapchat_lookup_controller_action_organization

        List of organizations
        """
        pass

    def test_snapchat_lookup_controller_action_preview(self) -> None:
        """Test case for snapchat_lookup_controller_action_preview

        Preview the data
        """
        pass


if __name__ == '__main__':
    unittest.main()
