# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_controller_auth(self) -> None:
        """Test case for auth_controller_auth

        """
        pass

    def test_auth_controller_auth_mfa(self) -> None:
        """Test case for auth_controller_auth_mfa

        """
        pass

    def test_auth_controller_refresh(self) -> None:
        """Test case for auth_controller_refresh

        """
        pass

    def test_auth_controller_revoke(self) -> None:
        """Test case for auth_controller_revoke

        """
        pass


if __name__ == '__main__':
    unittest.main()
