# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_pinterest_api import ConnectorsPinterestApi


class TestConnectorsPinterestApi(unittest.TestCase):
    """ConnectorsPinterestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsPinterestApi()

    def tearDown(self) -> None:
        pass

    def test_pinterest_controller_action_advertiser(self) -> None:
        """Test case for pinterest_controller_action_advertiser

        List of ads accounts
        """
        pass

    def test_pinterest_controller_action_authorization(self) -> None:
        """Test case for pinterest_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_pinterest_controller_action_click_window_days(self) -> None:
        """Test case for pinterest_controller_action_click_window_days

        List of click windows
        """
        pass

    def test_pinterest_controller_action_column(self) -> None:
        """Test case for pinterest_controller_action_column

        List of columns
        """
        pass

    def test_pinterest_controller_action_conversion_time(self) -> None:
        """Test case for pinterest_controller_action_conversion_time

        List of conversion times
        """
        pass

    def test_pinterest_controller_action_data_label(self) -> None:
        """Test case for pinterest_controller_action_data_label

        List of data labels
        """
        pass

    def test_pinterest_controller_action_date_range(self) -> None:
        """Test case for pinterest_controller_action_date_range

        List of date ranges
        """
        pass

    def test_pinterest_controller_action_engagement_window_days(self) -> None:
        """Test case for pinterest_controller_action_engagement_window_days

        List of engagement windows
        """
        pass

    def test_pinterest_controller_action_granularity(self) -> None:
        """Test case for pinterest_controller_action_granularity

        List of time breakdowns
        """
        pass

    def test_pinterest_controller_action_load(self) -> None:
        """Test case for pinterest_controller_action_load

        Create Pinterest source
        """
        pass

    def test_pinterest_controller_action_preview(self) -> None:
        """Test case for pinterest_controller_action_preview

        Preview the data
        """
        pass

    def test_pinterest_controller_action_report_level(self) -> None:
        """Test case for pinterest_controller_action_report_level

        List of reporting levels
        """
        pass

    def test_pinterest_controller_action_view_window_days(self) -> None:
        """Test case for pinterest_controller_action_view_window_days

        List of view windows
        """
        pass


if __name__ == '__main__':
    unittest.main()
