# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_intercom_api import ServicesIntercomApi


class TestServicesIntercomApi(unittest.TestCase):
    """ServicesIntercomApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesIntercomApi()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_intercom_intercom_authorizer_action_region(self) -> None:
        """Test case for app_authorizer_intercom_intercom_authorizer_action_region

        List of region options
        """
        pass

    def test_app_authorizer_intercom_intercom_authorizer_get_authorization_url(self) -> None:
        """Test case for app_authorizer_intercom_intercom_authorizer_get_authorization_url

        Builds redirect URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
