# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.well_known_controller_keys200_response import WellKnownControllerKeys200Response

class TestWellKnownControllerKeys200Response(unittest.TestCase):
    """WellKnownControllerKeys200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WellKnownControllerKeys200Response:
        """Test WellKnownControllerKeys200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WellKnownControllerKeys200Response`
        """
        model = WellKnownControllerKeys200Response()
        if include_optional:
            return WellKnownControllerKeys200Response(
                keys = [
                    [
                        openapi_client.models.jwks_inner.JWKS_inner(
                            alg = '', 
                            kty = '', 
                            use = '', 
                            key_ops = '', 
                            kid = '', 
                            crv = '', 
                            x = '', 
                            y = '', )
                        ]
                    ]
            )
        else:
            return WellKnownControllerKeys200Response(
        )
        """

    def testWellKnownControllerKeys200Response(self):
        """Test WellKnownControllerKeys200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
