# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_google_ads_api import ConnectorsGoogleAdsApi


class TestConnectorsGoogleAdsApi(unittest.TestCase):
    """ConnectorsGoogleAdsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsGoogleAdsApi()

    def tearDown(self) -> None:
        pass

    def test_google_ads_controller_action_attribute(self) -> None:
        """Test case for google_ads_controller_action_attribute

        List of all attributes
        """
        pass

    def test_google_ads_controller_action_authorization(self) -> None:
        """Test case for google_ads_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_google_ads_controller_action_customer(self) -> None:
        """Test case for google_ads_controller_action_customer

        List of customers
        """
        pass

    def test_google_ads_controller_action_customer_client(self) -> None:
        """Test case for google_ads_controller_action_customer_client

        List of clients
        """
        pass

    def test_google_ads_controller_action_load(self) -> None:
        """Test case for google_ads_controller_action_load

        Create GoogleAds source
        """
        pass

    def test_google_ads_controller_action_metric(self) -> None:
        """Test case for google_ads_controller_action_metric

        List of metric objects
        """
        pass

    def test_google_ads_controller_action_preview(self) -> None:
        """Test case for google_ads_controller_action_preview

        Preview the data
        """
        pass

    def test_google_ads_controller_action_report_type(self) -> None:
        """Test case for google_ads_controller_action_report_type

        List of all report types
        """
        pass

    def test_google_ads_controller_action_segment(self) -> None:
        """Test case for google_ads_controller_action_segment

        List of all segments
        """
        pass


if __name__ == '__main__':
    unittest.main()
