# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.well_known_api import WellKnownApi


class TestWellKnownApi(unittest.TestCase):
    """WellKnownApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WellKnownApi()

    def tearDown(self) -> None:
        pass

    def test_well_known_controller_keys(self) -> None:
        """Test case for well_known_controller_keys

        """
        pass


if __name__ == '__main__':
    unittest.main()
