# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connectors_instagram_media_api import ConnectorsInstagramMediaApi


class TestConnectorsInstagramMediaApi(unittest.TestCase):
    """ConnectorsInstagramMediaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsInstagramMediaApi()

    def tearDown(self) -> None:
        pass

    def test_instagram_media_controller_action_account(self) -> None:
        """Test case for instagram_media_controller_action_account

        List of accounts
        """
        pass

    def test_instagram_media_controller_action_attribute(self) -> None:
        """Test case for instagram_media_controller_action_attribute

        List of attributes
        """
        pass

    def test_instagram_media_controller_action_authorization(self) -> None:
        """Test case for instagram_media_controller_action_authorization

        List of authorization objects
        """
        pass

    def test_instagram_media_controller_action_load(self) -> None:
        """Test case for instagram_media_controller_action_load

        Create Instagram Media source
        """
        pass

    def test_instagram_media_controller_action_preview(self) -> None:
        """Test case for instagram_media_controller_action_preview

        Preview the data
        """
        pass


if __name__ == '__main__':
    unittest.main()
