# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_google_search_console_custom_google_search_console_custom_authorizer_new_o_auth_callback_request import AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest

class TestAppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest(unittest.TestCase):
    """AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest:
        """Test AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest`
        """
        model = AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest()
        if include_optional:
            return AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest(
                callback_url = 'https://my.app.com/callback?code=aaaaBBBBccc1234',
                config = openapi_client.models.google_search_console_custom_dto_authorizer.GoogleSearchConsoleCustomDtoAuthorizer(
                    label = '', 
                    client_id = '', 
                    client_secret = '', 
                    redirect_uri = '', )
            )
        else:
            return AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest(
        )
        """

    def testAppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest(self):
        """Test AppAuthorizerGoogleSearchConsoleCustomGoogleSearchConsoleCustomAuthorizerNewOAuthCallbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
