# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.destinations_pipedream_api import DestinationsPipedreamApi


class TestDestinationsPipedreamApi(unittest.TestCase):
    """DestinationsPipedreamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DestinationsPipedreamApi()

    def tearDown(self) -> None:
        pass

    def test_app_destination_pipedream_pipedream_destination_action_authorization(self) -> None:
        """Test case for app_destination_pipedream_pipedream_destination_action_authorization

        List of authorization objects
        """
        pass

    def test_app_destination_pipedream_pipedream_destination_action_destination_fields(self) -> None:
        """Test case for app_destination_pipedream_pipedream_destination_action_destination_fields

        List of destination fields
        """
        pass

    def test_app_destination_pipedream_pipedream_destination_action_source_fields(self) -> None:
        """Test case for app_destination_pipedream_pipedream_destination_action_source_fields

        List of source fields
        """
        pass

    def test_app_destination_pipedream_pipedream_destination_action_write_modes(self) -> None:
        """Test case for app_destination_pipedream_pipedream_destination_action_write_modes

        List of write modes
        """
        pass

    def test_app_destination_pipedream_pipedream_destination_create(self) -> None:
        """Test case for app_destination_pipedream_pipedream_destination_create

        Create destination
        """
        pass


if __name__ == '__main__':
    unittest.main()
