# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_facebook_page_access_token_facebook_page_access_token_authorizer_new_request import AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest

class TestAppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest(unittest.TestCase):
    """AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest:
        """Test AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest`
        """
        model = AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest()
        if include_optional:
            return AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest(
                service = 'facebook_page_access_token',
                data = openapi_client.models.facebook_pages_access_token_dto_authorizer.FacebookPagesAccessTokenDtoAuthorizer()
            )
        else:
            return AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest(
        )
        """

    def testAppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest(self):
        """Test AppAuthorizerFacebookPageAccessTokenFacebookPageAccessTokenAuthorizerNewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
