# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_authorizer_amazon_ads_custom_amazon_ads_custom_authorizer_new_o_auth_url_request import AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest

class TestAppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest(unittest.TestCase):
    """AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest:
        """Test AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest`
        """
        model = AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest()
        if include_optional:
            return AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest(
                config = [
                    openapi_client.models.app_authorizer_amazon_ads_custom_amazon_ads_custom_authorizer_new_o_auth_url_request_config_inner.appAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrl_request_config_inner(
                        client_id = '', 
                        redirect_uri = '', 
                        scopes = [
                            ''
                            ], )
                    ],
                state = '',
                service_id = ''
            )
        else:
            return AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest(
        )
        """

    def testAppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest(self):
        """Test AppAuthorizerAmazonAdsCustomAmazonAdsCustomAuthorizerNewOAuthUrlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
