# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_aws_pgsql_api import ServicesAwsPgsqlApi


class TestServicesAwsPgsqlApi(unittest.TestCase):
    """ServicesAwsPgsqlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesAwsPgsqlApi()

    def tearDown(self) -> None:
        pass

    def test_app_authorizer_aws_pgsql_aws_pgsql_authorizer_action_ssl(self) -> None:
        """Test case for app_authorizer_aws_pgsql_aws_pgsql_authorizer_action_ssl

        List of SSL options
        """
        pass

    def test_app_authorizer_aws_pgsql_aws_pgsql_authorizer_create_service(self) -> None:
        """Test case for app_authorizer_aws_pgsql_aws_pgsql_authorizer_create_service

        Create service
        """
        pass


if __name__ == '__main__':
    unittest.main()
