# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.destinations_panoply_api import DestinationsPanoplyApi


class TestDestinationsPanoplyApi(unittest.TestCase):
    """DestinationsPanoplyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DestinationsPanoplyApi()

    def tearDown(self) -> None:
        pass

    def test_app_destination_panoply_panoply_destination_action_authorization(self) -> None:
        """Test case for app_destination_panoply_panoply_destination_action_authorization

        List of authorization objects
        """
        pass

    def test_app_destination_panoply_panoply_destination_action_dataset(self) -> None:
        """Test case for app_destination_panoply_panoply_destination_action_dataset

        List of datasets
        """
        pass

    def test_app_destination_panoply_panoply_destination_action_project(self) -> None:
        """Test case for app_destination_panoply_panoply_destination_action_project

        List of projects
        """
        pass

    def test_app_destination_panoply_panoply_destination_action_write_modes(self) -> None:
        """Test case for app_destination_panoply_panoply_destination_action_write_modes

        List of write modes
        """
        pass

    def test_app_destination_panoply_panoply_destination_create(self) -> None:
        """Test case for app_destination_panoply_panoply_destination_create

        Create destination
        """
        pass


if __name__ == '__main__':
    unittest.main()
