# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ftp_additional_setting_trait import FtpAdditionalSettingTrait

class TestFtpAdditionalSettingTrait(unittest.TestCase):
    """FtpAdditionalSettingTrait unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FtpAdditionalSettingTrait:
        """Test FtpAdditionalSettingTrait
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FtpAdditionalSettingTrait`
        """
        model = FtpAdditionalSettingTrait()
        if include_optional:
            return FtpAdditionalSettingTrait(
                disable_explicit_tls = True,
                dial_timeout = 56,
                shut_timeout = 56,
                disable_epsv = True,
                disable_utf8 = True,
                disable_mlsd = True,
                mdtm_write = True
            )
        else:
            return FtpAdditionalSettingTrait(
        )
        """

    def testFtpAdditionalSettingTrait(self):
        """Test FtpAdditionalSettingTrait"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
