# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ConnectorListResponse(BaseModel):
    """
    ConnectorListResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    categories: Optional[List[StrictStr]] = None
    group: Optional[StrictStr] = None
    customers: Optional[List[StrictInt]] = None
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    icon: Optional[StrictStr] = None
    icon_url: Optional[StrictStr] = Field(default=None, alias="iconUrl")
    services: Optional[List[Any]] = None
    priority: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "label", "tags", "categories", "group", "customers", "createdAt", "icon", "iconUrl", "services", "priority"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectorListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if group (nullable) is None
        # and model_fields_set contains the field
        if self.group is None and "group" in self.model_fields_set:
            _dict['group'] = None

        # set to None if customers (nullable) is None
        # and model_fields_set contains the field
        if self.customers is None and "customers" in self.model_fields_set:
            _dict['customers'] = None

        # set to None if icon_url (nullable) is None
        # and model_fields_set contains the field
        if self.icon_url is None and "icon_url" in self.model_fields_set:
            _dict['iconUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectorListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "tags": obj.get("tags"),
            "categories": obj.get("categories"),
            "group": obj.get("group"),
            "customers": obj.get("customers"),
            "createdAt": obj.get("createdAt"),
            "icon": obj.get("icon"),
            "iconUrl": obj.get("iconUrl"),
            "services": obj.get("services"),
            "priority": obj.get("priority")
        })
        return _obj


