# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GoogleAdsConnectorForm(BaseModel):
    """
    GoogleAdsConnectorForm
    """ # noqa: E501
    ensure_data_types: Optional[Dict[str, Any]] = Field(default=None, description="Enforcing data types", alias="ensureDataTypes")
    allow_empty: Optional[StrictBool] = Field(default=True, alias="allowEmpty")
    nullable_fields: Optional[StrictBool] = Field(default=True, alias="nullableFields")
    connector_id: StrictStr = Field(alias="connectorId")
    template_id: StrictStr = Field(alias="templateId")
    strategy: Optional[StrictStr] = Field(default=None, description="Use storageStrategy instead.")
    storage_strategy: StrictStr = Field(alias="storageStrategy")
    label: Optional[StrictStr] = Field(default=None, description="Label of the source")
    o_auth_id: Optional[StrictStr] = Field(default=None, alias="oAuthId")
    date_range: Optional[StrictStr] = Field(default=None, description="Data range expression", alias="dateRange")
    use_dataddo_hash: Optional[StrictBool] = Field(default=None, description="Include Dataddo hash (to be used for upsert)", alias="useDataddoHash")
    google_customer_id: Optional[StrictStr] = Field(default=None, description="Google Customer Id", alias="googleCustomerId")
    customer_client_id: Optional[StrictStr] = Field(default=None, description="Google Customer Client Id", alias="customerClientId")
    attribute: Optional[List[StrictStr]] = None
    segment: Optional[List[StrictStr]] = None
    metric: Optional[List[StrictStr]] = None
    report_type: Optional[StrictStr] = Field(default=None, alias="reportType")
    where_filter: Optional[StrictStr] = Field(default=None, alias="whereFilter")
    __properties: ClassVar[List[str]] = ["ensureDataTypes", "allowEmpty", "nullableFields", "connectorId", "templateId", "strategy", "storageStrategy", "label", "oAuthId", "dateRange", "useDataddoHash", "googleCustomerId", "customerClientId", "attribute", "segment", "metric", "reportType", "whereFilter"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GoogleAdsConnectorForm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if o_auth_id (nullable) is None
        # and model_fields_set contains the field
        if self.o_auth_id is None and "o_auth_id" in self.model_fields_set:
            _dict['oAuthId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GoogleAdsConnectorForm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ensureDataTypes": obj.get("ensureDataTypes"),
            "allowEmpty": obj.get("allowEmpty") if obj.get("allowEmpty") is not None else True,
            "nullableFields": obj.get("nullableFields") if obj.get("nullableFields") is not None else True,
            "connectorId": obj.get("connectorId"),
            "templateId": obj.get("templateId"),
            "strategy": obj.get("strategy"),
            "storageStrategy": obj.get("storageStrategy"),
            "label": obj.get("label"),
            "oAuthId": obj.get("oAuthId"),
            "dateRange": obj.get("dateRange"),
            "useDataddoHash": obj.get("useDataddoHash"),
            "googleCustomerId": obj.get("googleCustomerId"),
            "customerClientId": obj.get("customerClientId"),
            "attribute": obj.get("attribute"),
            "segment": obj.get("segment"),
            "metric": obj.get("metric"),
            "reportType": obj.get("reportType"),
            "whereFilter": obj.get("whereFilter")
        })
        return _obj


