# coding: utf-8

"""
    Dataddo Headless BETA API

    Dataddo Headless BETA API

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RunExtractionRequest(BaseModel):
    """
    RunExtractionRequest
    """ # noqa: E501
    url: Optional[StrictStr] = None
    limit: Optional[StrictStr] = None
    date_from: Optional[StrictStr] = Field(default=None, description="A \"Y-m-d\" formatted value", alias="dateFrom")
    date_to: Optional[StrictStr] = Field(default=None, description="A \"Y-m-d\" formatted value", alias="dateTo")
    date_range_expression: Optional[StrictStr] = Field(default=None, description="A \"{{1d1}}\" formatted value", alias="dateRangeExpression")
    storage_strategy: Optional[StrictStr] = Field(default=None, alias="storageStrategy")
    __properties: ClassVar[List[str]] = ["url", "limit", "dateFrom", "dateTo", "dateRangeExpression", "storageStrategy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunExtractionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if limit (nullable) is None
        # and model_fields_set contains the field
        if self.limit is None and "limit" in self.model_fields_set:
            _dict['limit'] = None

        # set to None if date_from (nullable) is None
        # and model_fields_set contains the field
        if self.date_from is None and "date_from" in self.model_fields_set:
            _dict['dateFrom'] = None

        # set to None if date_to (nullable) is None
        # and model_fields_set contains the field
        if self.date_to is None and "date_to" in self.model_fields_set:
            _dict['dateTo'] = None

        # set to None if date_range_expression (nullable) is None
        # and model_fields_set contains the field
        if self.date_range_expression is None and "date_range_expression" in self.model_fields_set:
            _dict['dateRangeExpression'] = None

        # set to None if storage_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.storage_strategy is None and "storage_strategy" in self.model_fields_set:
            _dict['storageStrategy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunExtractionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "limit": obj.get("limit"),
            "dateFrom": obj.get("dateFrom"),
            "dateTo": obj.get("dateTo"),
            "dateRangeExpression": obj.get("dateRangeExpression"),
            "storageStrategy": obj.get("storageStrategy")
        })
        return _obj


